# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"0\n\rMatrixRequest\x12\x0e\n\x06values\x18\x01 \x03(\x01\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\x05\" \n\x0eMatrixResponse\x12\x0e\n\x06values\x18\x01 \x03(\x01\x32\x45\n\x0eMathOperations\x12\x33\n\x0eMatrixMultiply\x12\x0e.MatrixRequest\x1a\x0f.MatrixResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MATRIXREQUEST']._serialized_start=17
  _globals['_MATRIXREQUEST']._serialized_end=65
  _globals['_MATRIXRESPONSE']._serialized_start=67
  _globals['_MATRIXRESPONSE']._serialized_end=99
  _globals['_MATHOPERATIONS']._serialized_start=101
  _globals['_MATHOPERATIONS']._serialized_end=170
# @@protoc_insertion_point(module_scope)
