# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class MathOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MatrixMultiply = channel.unary_unary(
                '/MathOperations/MatrixMultiply',
                request_serializer=service__pb2.MatrixRequest.SerializeToString,
                response_deserializer=service__pb2.MatrixResponse.FromString,
                )


class MathOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MatrixMultiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MathOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MatrixMultiply': grpc.unary_unary_rpc_method_handler(
                    servicer.MatrixMultiply,
                    request_deserializer=service__pb2.MatrixRequest.FromString,
                    response_serializer=service__pb2.MatrixResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MathOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MathOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MatrixMultiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MathOperations/MatrixMultiply',
            service__pb2.MatrixRequest.SerializeToString,
            service__pb2.MatrixResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
