# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1e\n\x0bNumberArray\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\x32\x43\n\x14NumberSortingService\x12+\n\x0bSortNumbers\x12\x0c.NumberArray\x1a\x0c.NumberArray\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NUMBERARRAY']._serialized_start=17
  _globals['_NUMBERARRAY']._serialized_end=47
  _globals['_NUMBERSORTINGSERVICE']._serialized_start=49
  _globals['_NUMBERSORTINGSERVICE']._serialized_end=116
# @@protoc_insertion_point(module_scope)
